version: '3.8'

services:
  silly-demo:
    build: .
    container_name: silly-demo-app
    volumes:
      - .:/app # Bind mount the current directory for development
      - /app/tmp # Avoid volume caching issues
    ports:
      - "8080:8080" # Expose internal port 8080
    environment:
      - GO_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=sillydemo
    depends_on:
      - db
    command: ["air"] # Run the hot-reloading tool

  nginx:
    image: nginx:latest
    container_name: silly-demo-nginx
    ports:
      - "80:80" # Expose NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - silly-demo

  db:
    image: postgres:15
    container_name: silly-demo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sillydemo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
